# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
#
# See https://goreleaser.com/customization/ for more information.
project_name: printver

before:
  hooks:
    - go mod tidy
builds:
  - env:
      - CGO_ENABLED=0
    binary: printver
    main: ./cmd/printver
    goos:
      # - linux
      - darwin
      # - windows
    goarch:
      - arm64
      # - amd64
    ldflags:
      # The v prefix is stripped by goreleaser, so we need to add it back.
      # https://goreleaser.com/customization/templates/#fnref:version-prefix
      - "-s -w -X main.version=v{{ .Version }}"

archives:
  - format: binary
    name_template: >-
      {{ .ProjectName }}_{{- tolower .Os }}_{{- if eq .Arch "amd64" }}x86_64{{- else }}{{ .Arch }}{{ end }}
checksum:
  disable: true
snapshot:
  name_template: "{{ incpatch .Version }}-next"
changelog:
  use: github-native
